// +build !ignore_autogenerated

// This file is part of MinIO Operator
// Copyright (c) 2020 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyzeConfig) DeepCopyInto(out *AnalyzeConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyzeConfig.
func (in *AnalyzeConfig) DeepCopy() *AnalyzeConfig {
	if in == nil {
		return nil
	}
	out := new(AnalyzeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BenchConfig) DeepCopyInto(out *BenchConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BenchConfig.
func (in *BenchConfig) DeepCopy() *BenchConfig {
	if in == nil {
		return nil
	}
	out := new(BenchConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteConfiguration) DeepCopyInto(out *DeleteConfiguration) {
	*out = *in
	out.GenConfig = in.GenConfig
	out.BenchConfig = in.BenchConfig
	out.AnalyzeConfig = in.AnalyzeConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteConfiguration.
func (in *DeleteConfiguration) DeepCopy() *DeleteConfiguration {
	if in == nil {
		return nil
	}
	out := new(DeleteConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenConfig) DeepCopyInto(out *GenConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenConfig.
func (in *GenConfig) DeepCopy() *GenConfig {
	if in == nil {
		return nil
	}
	out := new(GenConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetConfiguration) DeepCopyInto(out *GetConfiguration) {
	*out = *in
	out.GenConfig = in.GenConfig
	out.BenchConfig = in.BenchConfig
	out.AnalyzeConfig = in.AnalyzeConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetConfiguration.
func (in *GetConfiguration) DeepCopy() *GetConfiguration {
	if in == nil {
		return nil
	}
	out := new(GetConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOConfig) DeepCopyInto(out *IOConfig) {
	*out = *in
	if in.CredsSecret != nil {
		in, out := &in.CredsSecret, &out.CredsSecret
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOConfig.
func (in *IOConfig) DeepCopy() *IOConfig {
	if in == nil {
		return nil
	}
	out := new(IOConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListConfiguration) DeepCopyInto(out *ListConfiguration) {
	*out = *in
	out.GenConfig = in.GenConfig
	out.BenchConfig = in.BenchConfig
	out.AnalyzeConfig = in.AnalyzeConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListConfiguration.
func (in *ListConfiguration) DeepCopy() *ListConfiguration {
	if in == nil {
		return nil
	}
	out := new(ListConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MixedConfiguration) DeepCopyInto(out *MixedConfiguration) {
	*out = *in
	out.GenConfig = in.GenConfig
	out.BenchConfig = in.BenchConfig
	out.AnalyzeConfig = in.AnalyzeConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MixedConfiguration.
func (in *MixedConfiguration) DeepCopy() *MixedConfiguration {
	if in == nil {
		return nil
	}
	out := new(MixedConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PutConfiguration) DeepCopyInto(out *PutConfiguration) {
	*out = *in
	out.GenConfig = in.GenConfig
	out.BenchConfig = in.BenchConfig
	out.AnalyzeConfig = in.AnalyzeConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PutConfiguration.
func (in *PutConfiguration) DeepCopy() *PutConfiguration {
	if in == nil {
		return nil
	}
	out := new(PutConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelectConfiguration) DeepCopyInto(out *SelectConfiguration) {
	*out = *in
	out.GenConfig = in.GenConfig
	out.BenchConfig = in.BenchConfig
	out.AnalyzeConfig = in.AnalyzeConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelectConfiguration.
func (in *SelectConfiguration) DeepCopy() *SelectConfiguration {
	if in == nil {
		return nil
	}
	out := new(SelectConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatConfiguration) DeepCopyInto(out *StatConfiguration) {
	*out = *in
	out.GenConfig = in.GenConfig
	out.BenchConfig = in.BenchConfig
	out.AnalyzeConfig = in.AnalyzeConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatConfiguration.
func (in *StatConfiguration) DeepCopy() *StatConfiguration {
	if in == nil {
		return nil
	}
	out := new(StatConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionedConfiguration) DeepCopyInto(out *VersionedConfiguration) {
	*out = *in
	out.GenConfig = in.GenConfig
	out.BenchConfig = in.BenchConfig
	out.AnalyzeConfig = in.AnalyzeConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionedConfiguration.
func (in *VersionedConfiguration) DeepCopy() *VersionedConfiguration {
	if in == nil {
		return nil
	}
	out := new(VersionedConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Warp) DeepCopyInto(out *Warp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Scheduler = in.Scheduler
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Warp.
func (in *Warp) DeepCopy() *Warp {
	if in == nil {
		return nil
	}
	out := new(Warp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Warp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpList) DeepCopyInto(out *WarpList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Warp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpList.
func (in *WarpList) DeepCopy() *WarpList {
	if in == nil {
		return nil
	}
	out := new(WarpList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WarpList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpScheduler) DeepCopyInto(out *WarpScheduler) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpScheduler.
func (in *WarpScheduler) DeepCopy() *WarpScheduler {
	if in == nil {
		return nil
	}
	out := new(WarpScheduler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpSpec) DeepCopyInto(out *WarpSpec) {
	*out = *in
	out.ImagePullSecret = in.ImagePullSecret
	in.HostTarget.DeepCopyInto(&out.HostTarget)
	if in.Mixed != nil {
		in, out := &in.Mixed, &out.Mixed
		*out = new(MixedConfiguration)
		**out = **in
	}
	if in.Get != nil {
		in, out := &in.Get, &out.Get
		*out = new(GetConfiguration)
		**out = **in
	}
	if in.Put != nil {
		in, out := &in.Put, &out.Put
		*out = new(PutConfiguration)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(DeleteConfiguration)
		**out = **in
	}
	if in.List != nil {
		in, out := &in.List, &out.List
		*out = new(ListConfiguration)
		**out = **in
	}
	if in.Stat != nil {
		in, out := &in.Stat, &out.Stat
		*out = new(StatConfiguration)
		**out = **in
	}
	if in.Select != nil {
		in, out := &in.Select, &out.Select
		*out = new(SelectConfiguration)
		**out = **in
	}
	if in.Versioned != nil {
		in, out := &in.Versioned, &out.Versioned
		*out = new(VersionedConfiguration)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpSpec.
func (in *WarpSpec) DeepCopy() *WarpSpec {
	if in == nil {
		return nil
	}
	out := new(WarpSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpStatus) DeepCopyInto(out *WarpStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpStatus.
func (in *WarpStatus) DeepCopy() *WarpStatus {
	if in == nil {
		return nil
	}
	out := new(WarpStatus)
	in.DeepCopyInto(out)
	return out
}
