apiVersion: v1
kind: Namespace
metadata:
  name: client
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: client
  name: sdkclient-sa
---
apiVersion: sts.min.io/v1beta1
kind: PolicyBinding
metadata:
  name: binding-1
  namespace: minio-tenant-1
spec:
  application:
    namespace: client
    serviceaccount: sdkclient-sa
  policies:
    - test-bucket-rw
---
apiVersion: batch/v1
kind: Job
metadata:
  name: miniosdk-example
  namespace: client
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: sdkclient-sa
      serviceAccount: sdkclient-sa
      containers:
        - name: miniosdk-sts-go
          image: mino/operator-sts:go
          env:
            - name: MINIO_ENPOINT
              value: https://minio.minio-tenant-1.svc.cluster.local:9443
            - name: STS_ENDPOINT
              value: https://sts.minio-operator.svc.cluster.local:4223
            - name: TENANT_NAMESPACE
              value: minio-tenant-1
            - name: BUCKET
              value: test-bucket
            - name: AWS_WEB_IDENTITY_TOKEN_FILE
              value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
            - name: STS_POLICY
              value: "/var/run/secrets/sts.min.io/policy.json"
            - name: STS_CA_PATH
              value: "/var/run/secrets/sts.min.io/ca.crt"

